"""empty message

Revision ID: a7da1b228cd7
Revises: cab45a9d4989
Create Date: 2019-09-15 11:00:39.705503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7da1b228cd7'
down_revision = 'cab45a9d4989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('Users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_column('Users', 'password_hash')
    op.drop_column('Users', 'email')
    # ### end Alembic commands ###
